export {default as Iris} from 'iris/components/Iris'
export {default as Fshion} from 'iris/components/Fashion'
export {default as Number} from 'iris/components/Number'
export {default as NaverCrawler} from 'iris/components/NaverCrawler'
export {default as Stock} from 'iris/components/Stock'
